### ISSUE TITLE
Feature request: hotkeys for "Indicate cursor position" and "Show icon on click"

### ISSUE THREAD

**Issue by ChrisJohnTaylor** [Phaiax/Key-n-Stroke#68]
Terrific program for those of us who demo programs or teach how to use computers! Thanks!

A really nice enhancement would be to add user-definable hot-keys to toggle on/off the "Indicate cursor position" and "Show icons on click". And probably "Show keystroke History" as well, but I rarely use that, so it is not as critical for me.

With user-definable hotkeys, I could leave the program loaded all the time and just have things toggled off. when I want to demo something, I could quickly toggle on features I want. A lot of the time, I might want just "Indicate cursor position" and then just toggle on "Show icons on click" when I am demoing something where it is important that people understand if I am using a left-click, right-click or a modifier key, and then toggle that feature off again.

And, it these hot-keys could be added, I think it would also make sense to add an option to "Load when Windows starts" so it is always there and ready for use.

Thanks again!

**Comment by Phaiax** [comment]
First suggestion is implemented and will be part of next release. (But with only a single shortcut to toggle all enabled features on/off)

The start up suggestion is difficult to implement, because the programm does not install itself to a reliable location. But there are [many ways to run a programm on windows startup](https://www.ionos.com/digitalguide/server/configuration/windows-11-startup/).
